services:

  app:
    build:
      context: ../..
      dockerfile: docker/testing/Dockerfile
    image: webcis-api:testing
    container_name: webcis-api-testing
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - webcis
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  mariadb:
    image: mariadb:11
    container_name: webcis-mariadb-testing
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - webcis
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p$MARIADB_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s


  mailpit:
    image: axllent/mailpit
    container_name: webcis-mailpit-testing
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - webcis

networks:
  webcis:
